# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e222a7682d14f945a781e7803719d0073890d8b8665468965667335c0e06c2cff0b4a97612edb8750b949ecb48fa80c61eae9c3c13df871d89bf35783a1bed02

test:
  secret_key_base: 6883eb1f02bbbef686e4b5ae5d712914a2a98c31ddb8a63ab8703ea71f60f365392cea662649fc90da090ccdc58b6996589f3b53b499e185bda5d9c19ed19f74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
